---
# tasks file for common
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - 'ca-certificates'
      - 'curl'
      - 'gnupg'
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  shell:
    cmd: |
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg

- name: Get DEB architecture
  shell:
    cmd: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Copy content of directory 'files'
  ansible.builtin.copy:
    src: files/
    dest: /files/
    mode: preserve

- name: Pull Docker Compose stack
  shell:
    cmd: docker compose pull
    chdir: /files

- name: Deploy Docker Compose stack
  shell:
    cmd: docker compose up -d
    chdir: /files
