---
- name: Install aptitude using apt
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true
    force_apt_get: true

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
      - 'python3-pip'
      - 'virtualenv'
      - 'python3-setuptools'
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Copy content of directory 'files'
  ansible.builtin.copy:
    src: files/
    dest: /files/

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /files