accessLog: {}

providers:
  docker:
    network: backend_network 
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/conf"

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443

certificatesResolvers:
  certificato:
    acme:
      email: antoinereims28@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web